version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      go:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    groups:
      docker:
        patterns:
          - '*'
